### ISSUE TITLE
angular??

### ISSUE THREAD

**Issue by SerdarSanri** [bvaughn/briandavidvaughn#1]
Interesting, as a React core developer your own website is built with angular

**Comment by bvaughn** [comment]
You'll notice this repo [hasn't had a meaningful commit since 2015](https://github.com/bvaughn/briandavidvaughn/commits/master). At the time I created it, I was working at Google on the Google Cloud Platform team (which used Angular). Shortly afterward, I started working with React. I could spend some time to rewrite it but I'd rather work on open source projects that benefit others more than this website. 😄
